# MiniFactions Configuration

# Crafting Recipe Keys
# Core Blocks are no longer craftable - they are given to clan leaders automatically
# Claim Blocks: E = Emerald, R = Redstone Block, D = Diamond
# Defense Blocks: O = Obsidian, I = Iron Ingot/Block, C = Crying Obsidian, G = Gold Block, D = Diamond Block
# Explosives: G = Gunpowder, B = Button, R = Redstone/Redstone Block, P = Blaze Powder
#
# Defense Block Tiers:
# Tier 1: White Terracotta
# Tier 2: Light Gray Terracotta
# Tier 3: Brown Terracotta
# Tier 4: Gray Terracotta
# Tier 5: Black Terracotta

# Core Block Settings
core:
  max-level: 20
  points-on-break-percentage: 50
  beacon-effect: true
  # Outside block settings
  outside-blocks:
    enabled: true
    min-decay-time: 30 # minutes
    max-decay-time: 120 # minutes
    safe-distance: 5 # blocks from core that won't decay
    check-interval: 5 # minutes between decay checks
  # Detailed level configuration
  levels:
    # Level 1 (Starting level)
    1:
      area: 10
      defense-slots: 20
      claim-slots: 2
      door-slots: 1
      member-slots: 5
      upkeep-cost: 30
      upgrade-cost: 200
      # Core blocks are no longer craftable
      # They are given to clan leaders automatically
    # Level 2
    2:
      area: 15
      defense-slots: 25
      claim-slots: 5
      door-slots: 2
      member-slots: 5
      upkeep-cost: 150
      upgrade-cost: 300
      # Core blocks are no longer craftable
      # They are given to clan leaders automatically
    # Level 3
    3:
      area: 25
      defense-slots: 30
      claim-slots: 4
      door-slots: 3
      member-slots: 5
      upkeep-cost: 200
      upgrade-cost: 400
      # Core blocks are no longer craftable
      # They are given to clan leaders automatically
    # Level 4
    4:
      area: 25
      defense-slots: 35
      claim-slots: 5
      door-slots: 4
      member-slots: 5
      upkeep-cost: 250
      upgrade-cost: 600
      recipe:
        - "DIAMOND:8"
        - "GOLD_BLOCK:4"
        - "OBSIDIAN:64"
    # Level 5
    5:
      area: 25
      defense-slots: 40
      claim-slots: 6
      door-slots: 5
      member-slots: 5
      upkeep-cost: 300
      upgrade-cost: 800
      recipe:
        - "DIAMOND:16"
        - "GOLD_BLOCK:8"
        - "OBSIDIAN:128"
    # Level 6-10 (Moderate progression)
    6:
      area: 25
      defense-slots: 45
      claim-slots: 7
      door-slots: 5
      member-slots: 5
      upkeep-cost: 350
      upgrade-cost: 900
      recipe:
        - "DIAMOND:32"
        - "GOLD_BLOCK:16"
        - "OBSIDIAN:256"
    7:
      area: 25
      defense-slots: 50
      claim-slots: 8
      door-slots: 5
      member-slots: 5
      upkeep-cost: 400
      upgrade-cost: 1000
      recipe:
        - "DIAMOND_BLOCK:1"
        - "GOLD_BLOCK:32"
        - "OBSIDIAN:512"
    8:
      area: 25
      defense-slots: 55
      claim-slots: 9
      door-slots: 5
      member-slots: 5
      upkeep-cost: 450
      upgrade-cost: 1500
      recipe:
        - "DIAMOND_BLOCK:2"
        - "GOLD_BLOCK:64"
        - "NETHERITE_SCRAP:1"
    9:
      area: 25
      defense-slots: 60
      claim-slots: 10
      door-slots: 5
      member-slots: 5
      upkeep-cost: 500
      upgrade-cost: 2000
      recipe:
        - "DIAMOND_BLOCK:4"
        - "EMERALD_BLOCK:2"
        - "NETHERITE_SCRAP:2"
    10:
      area: 25
      defense-slots: 65
      claim-slots: 12
      door-slots: 5
      member-slots: 5
      upkeep-cost: 600
      upgrade-cost: 2500
      recipe:
        - "DIAMOND_BLOCK:8"
        - "EMERALD_BLOCK:4"
        - "NETHERITE_SCRAP:4"
    # Level 11-20 (Advanced progression - significant jumps every 5 levels)
    11:
      area: 25
      defense-slots: 70
      claim-slots: 13
      door-slots: 5
      member-slots: 5
      upkeep-cost: 700
      upgrade-cost: 3000
      recipe:
        - "DIAMOND_BLOCK:16"
        - "EMERALD_BLOCK:8"
        - "NETHERITE_SCRAP:8"
    12:
      area: 25
      defense-slots: 75
      claim-slots: 14
      door-slots: 5
      member-slots: 5
      upkeep-cost: 800
      upgrade-cost: 4000
      recipe:
        - "DIAMOND_BLOCK:32"
        - "EMERALD_BLOCK:16"
        - "NETHERITE_INGOT:1"
    13:
      area: 25
      defense-slots: 80
      claim-slots: 15
      door-slots: 5
      member-slots: 5
      upkeep-cost: 900
      upgrade-cost: 5000
      recipe:
        - "DIAMOND_BLOCK:64"
        - "EMERALD_BLOCK:32"
        - "NETHERITE_INGOT:2"
    14:
      area: 25
      defense-slots: 85
      claim-slots: 16
      door-slots: 5
      member-slots: 5
      upkeep-cost: 1000
      upgrade-cost: 6000
      recipe:
        - "DIAMOND_BLOCK:128"
        - "EMERALD_BLOCK:64"
        - "NETHERITE_INGOT:4"
    15:
      area: 25
      defense-slots: 90
      claim-slots: 18
      door-slots: 5
      member-slots: 5
      upkeep-cost: 1200
      upgrade-cost: 8000
      recipe:
        - "DIAMOND_BLOCK:256"
        - "EMERALD_BLOCK:128"
        - "NETHERITE_BLOCK:1"
    16:
      area: 25
      defense-slots: 95
      claim-slots: 19
      door-slots: 5
      member-slots: 5
      upkeep-cost: 1400
      upgrade-cost: 9000
      recipe:
        - "DIAMOND_BLOCK:512"
        - "EMERALD_BLOCK:256"
        - "NETHERITE_BLOCK:2"
    17:
      area: 25
      defense-slots: 100
      claim-slots: 20
      door-slots: 5
      member-slots: 5
      upkeep-cost: 1600
      upgrade-cost: 10000
      recipe:
        - "DIAMOND_BLOCK:1024"
        - "EMERALD_BLOCK:512"
        - "NETHERITE_BLOCK:4"
    18:
      area: 25
      defense-slots: 115
      claim-slots: 21
      door-slots: 5
      member-slots: 5
      upkeep-cost: 1800
      upgrade-cost: 11000
      recipe:
        - "DIAMOND_BLOCK:2048"
        - "EMERALD_BLOCK:1024"
        - "NETHERITE_BLOCK:8"
    19:
      area: 25
      defense-slots: 150
      claim-slots: 22
      door-slots: 5
      member-slots: 5
      upkeep-cost: 2000
      upgrade-cost: 15000
      recipe:
        - "DIAMOND_BLOCK:4096"
        - "EMERALD_BLOCK:2048"
        - "NETHERITE_BLOCK:16"
    20:
      area: 25
      defense-slots: 200
      claim-slots: 25
      door-slots: 10
      member-slots: 5
      upkeep-cost: 20000
      # No upgrade cost for max level
      recipe:
        - "DIAMOND_BLOCK:8192"
        - "EMERALD_BLOCK:4096"
        - "NETHERITE_BLOCK:32"
  upkeep:
    enabled: true
    payment-interval: 24 # hours

# Global Upkeep Settings
upkeep:
  enabled: true
  check-interval: 1 # hours between upkeep checks
  warning-time: 6 # hours before upkeep is due to send warnings
  # Core Block Upkeep
  core:
    enabled: true
    penalty-type: "LEVEL_REDUCTION" # LEVEL_REDUCTION, POINT_PENALTY, NONE
    point-penalty-percentage: 10 # % of points to deduct if penalty-type is POINT_PENALTY
    level-reduction: 1 # levels to reduce if penalty-type is LEVEL_REDUCTION
    grace-period: 10 # hours before applying penalties
  # Claim Block Upkeep
  claim:
    enabled: true
    penalty-type: "LEVEL_REDUCTION" # LEVEL_REDUCTION, POINT_GENERATION_STOP, DESTRUCTION
    level-reduction: 1 # levels to reduce if penalty-type is LEVEL_REDUCTION
    grace-period: 24 # hours before applying penalties
  # Defense Block Upkeep
  defense:
    enabled: true
    penalty-type: "TIER_REDUCTION" # TIER_REDUCTION, DESTRUCTION
    tier-reduction: 1 # tiers to reduce if penalty-type is TIER_REDUCTION
    grace-period: 10 # hours before applying penalties
  # Clan Door Upkeep
  door:
    enabled: true
    penalty-type: "DESTRUCTION" # PUBLIC_ACCESS, DESTRUCTION
    grace-period: 2 # hours before applying penalties

# Claim Block Settings
claim:
  max-upgrade-level: 5
  levels:
    # Level 1 (Base)
    1:
      points-per-day: 10
      upgrade-cost: 100
      recipe-pattern:
        - "EEE"
        - "ERE"
        - "EEE"
      recipe-key:
        E: EMERALD
        R: REDSTONE_BLOCK
    # Level 2
    2:
      points-per-day: 50
      upgrade-cost: 200
      upgrade-items:
        - "EMERALD:16"
        - "REDSTONE_BLOCK:4"
    # Level 3
    3:
      points-per-day: 100
      upgrade-cost: 250
      upgrade-items:
        - "EMERALD:32"
        - "REDSTONE_BLOCK:8"
    # Level 4
    4:
      points-per-day: 150
      upgrade-cost: 300
      upgrade-items:
        - "EMERALD_BLOCK:1"
        - "REDSTONE_BLOCK:16"
    # Level 5 (Max)
    5:
      points-per-day: 200
      upgrade-items:
        - "EMERALD_BLOCK:2"
        - "REDSTONE_BLOCK:32"

# Defense Block Settings
defense:
  max-tier: 5
  min-decay-time: 1 # hours
  max-decay-time: 24 # hours
  tiers:
    # Tier 1 (Basic)
    1:
      cost: 100
      decay-time: 1 # hours
      recipe-pattern:
        - "OOO"
        - "OIO"
        - "OOO"
      recipe-key:
        O: OBSIDIAN
        I: IRON_INGOT
    # Tier 2
    2:
      cost: 200
      decay-time: 5 # hours
      recipe:
        - "OBSIDIAN:16"
        - "IRON_BLOCK:1"
    # Tier 3
    3:
      cost: 400
      decay-time: 7 # hours
      recipe:
        - "OBSIDIAN:32"
        - "IRON_BLOCK:2"
    # Tier 4
    4:
      cost: 800
      decay-time: 9 # hours
      recipe:
        - "OBSIDIAN:64"
        - "IRON_BLOCK:4"
    # Tier 5
    5:
      cost: 1600
      decay-time: 10 # hours
      recipe:
        - "OBSIDIAN:128"
        - "GOLD_BLOCK:1"

# Raiding Settings
raiding:
  explosive-fuse-time: 6 # seconds
  explosives:
    # Tier 1 (Basic)
    1:
      fuse-time: 25 # seconds
      recipe-pattern:
        - "GBG"
        - "BRB"
        - "GBG"
      recipe-key:
        G: GUNPOWDER
        B: STONE_BUTTON
        R: REDSTONE_BLOCK
    # Tier 2
    2:
      fuse-time: 20 # seconds
      recipe:
        - "STONE_BUTTON:4"
        - "GUNPOWDER:8"
        - "REDSTONE:16"
    # Tier 3
    3:
      fuse-time: 15 # seconds
      recipe:
        - "STONE_BUTTON:8"
        - "GUNPOWDER:16"
        - "REDSTONE:32"
    # Tier 4
    4:
      fuse-time: 10 # seconds
      recipe:
        - "STONE_BUTTON:12"
        - "GUNPOWDER:24"
        - "REDSTONE:64"
    # Tier 5
    5:
      fuse-time: 15 # seconds
      recipe:
        - "STONE_BUTTON:16"
        - "GUNPOWDER:32"
        - "REDSTONE_BLOCK:1"
# Clan Settings
clan:
  max-members: 5
  max-members-per-level: 0
  name-min-length: 4
  name-max-length: 16

# KOTH Settings
koth:
  enabled: true
  capture-time: 200  # seconds
  reward-points: 1000
  announce-interval: 60 # seconds

# PvP Settings
pvp:
  kill-points: 5
  death-penalty: 5

# Database Settings
database:
  type: "YAML" # YAML, MySQL, SQLite
  mysql:
    host: "localhost"
    port: 3306
    database: "minifactions"
    username: "root"
    password: "password"
    ssl: false
  sqlite:
    file: "database.db"
